name: Build

on:
  push:
    paths-ignore:
      - "**.md"
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: chmod +x gradlew && ./gradlew build --no-daemon

      - name: Upload Mod
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/libs
