name: Build

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '**/LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '2'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
          check-latest: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Undo Commit If Build Fails
        if: ${{ github.event_name == 'push' && failure() }}
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull
          git reset --hard HEAD~1
          git push --force-with-lease

      - name: Upload
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: upload
          path: ./build/libs/
